name: Download MLJ Cheatsheet

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Download file
        run: |
          curl -o mlj_cheatsheet.md https://raw.githubusercontent.com/alan-turing-institute/MLJ.jl/dev/docs/src/mlj_cheatsheet.md
        
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add mlj_cheatsheet.md
          git commit -m "Update MLJ cheatsheet"
          git push
