name: Generate Model Browser

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run-julia:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download file
        run: |
          curl -o src/lib/Data/model_docstring_tools.jl https://raw.githubusercontent.com/JuliaAI/MLJ.jl/dev/docs/model_docstring_tools.jl

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1'
          
      - name: Run and Install dependencies
        run: julia -e 'using Pkg; Pkg.add("MLJBase"); Pkg; Pkg.add("MLJ"); using MLJBase; using MLJ; include("model_docstring_tools.jl")'

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add src/lib/Data/model_browser.md
          git commit -m 'Update model_browser.md'
          git push
